### ISSUE TITLE
Command progress

### ISSUE THREAD

**Issue by ZimGil** [ZimGil/Angular-cli-ui#41]
The server should send the running process progress (as a `number` between 0-100) back to the client so the client will be able to block the user from sending other commands on the same project.

@ortichon is this achievable using our current server structure or do we need to use `spwan` or `socket`?

**Comment by ortichon** [comment]
@ZimGil how would you know what's the progress state?
we should avoid multiple commands while the server still working on the previous, but I'm not sure that Angular-CLI can give us progress event.
please investigate this issue and write your results here.

**Comment by ZimGil** [comment]
@ortichon 
> we should avoid multiple commands while the server still working on the previous

I've tried sending the `response` on `close` event but on a long task such as `new` the client `timeout` waiting to the `response`.
Should we change the timeout setting of `HttpClient` to avoid this or could we send an `Observable` and `subscribe()` to it on the client side?

**Comment by ortichon** [comment]
do you mean that we use synchronous calls on the client side???
It should be Asynchronous....

**Comment by ZimGil** [comment]
No, I miss-wrote.
I meant that now we only send text back to the client?
Could we send an object - let's say - `isDoneExecuting: boolean` that will let the client know when the server is done?

**Comment by ZimGil** [comment]
@ortichon if we send the response back to the client only when the server finishes creating the new project, wouldn't the client timeout from the server?

**Comment by ZimGil** [comment]
This is being solved on another issue.
